// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArdgXGCiLp8snlf9q4gYVAT_7YuCb7cDc',
    appId: '1:580082342311:web:a5ee87bf50c542bb23fe82',
    messagingSenderId: '580082342311',
    projectId: 'expense-app-9e7f4',
    authDomain: 'expense-app-9e7f4.firebaseapp.com',
    storageBucket: 'expense-app-9e7f4.appspot.com',
    measurementId: 'G-LHFZQG7GD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE4bHIX_atEeaPIh5Z72tMBVLCHh1NgWk',
    appId: '1:580082342311:android:b39409fdeefe241a23fe82',
    messagingSenderId: '580082342311',
    projectId: 'expense-app-9e7f4',
    storageBucket: 'expense-app-9e7f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANbMS5SflKSKOqO_oB_q11FuEyt76OGcE',
    appId: '1:580082342311:ios:5052efcd2d21971b23fe82',
    messagingSenderId: '580082342311',
    projectId: 'expense-app-9e7f4',
    storageBucket: 'expense-app-9e7f4.appspot.com',
    iosClientId: '580082342311-a17n6mb4a7jq88oihmbbtvh1rlhtv6lq.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseApp',
  );
}
